language: node_js
node_js:
 - "4.2.4"
 
os:
 - linux
 
install:
  - node --version
  - npm --version
  - git --version
  - npm install --no-optional
  
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-dev libboost-date-time-dev unixodbc-dev
  - mysql --version 
  - sqlcmd –S miroculuspct.database.windows.net – U miroculus – P Pa$$word1 -Q "Select @@version;"

script: npm test
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec