language: node_js
node_js:
 - "4.2.4"
 
os:
 - linux
 
install:
  - node --version
  - npm --version
  - git --version
  - npm install --no-optional
  
before_script:
  - wget http://download.microsoft.com/download/B/C/D/BCDD264C-7517-4B7D-8159-C99FC5535680/RedHat6/msodbcsql-11.0.2270.0.tar.gz
  - tar -zxvf msodbcsql-11.0.2270.0.tar.gz
  - sudo bash install.sh install --accept-license --force
  - sudo apt-get install openssl libkrb5-3 libc6 e2fsprogs
  - sudo ln -s /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 /usr/lib/x86_64-linux-gnu/libcrypto.so.10;
  - sudo ln -s /lib/x86_64-linux-gnu/libssl.so.1.0.0 /usr/lib/x86_64-linux-gnu/libssl.so.10;
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libodbcinst.so.2.0.0 /usr/lib/x86_64-linux-gnu/libodbcinst.so.1;
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libodbc.so.2.0.0 /usr/lib/x86_64-linux-gnu/libodbc.so.1
  - sqlcmd –S miroculuspct.database.windows.net – U miroculus – P Pa$$word1 -Q "Select @@version;"

script: npm test
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec